module CssClasses exposing (..)

type Classes
  = Navbar
  | Sidebar
  | BottomBar
  | Container
  | MenuToggler
  | SidebarActive
  | SearchInput
  | NavGroup
  | Logo
  | ProgressGroup
  | ProgressBar
  | Progress
  | FontSmall
  | FontMedium
  | Controls
  | ControlIcon
  | ControlButtons
  | NowPlaying
  | AlbumCover
  | MusicTitle
  | MusicInfo
  | SoundControl
  | UserProfile
  | UserImage
  | RoundedImage
  | Icon
  | Songs
  | SongItem
  | SongTitle
  | SongAlbumTitle
  | SongCover
  | SongDescription
  | IsPlaying
  | BigSearch
  | Content
  | Main
  | SearchResults
  | ArtistResult
  | ImageWrapper
  | SidebarLink
  | Active
  | SavePlaylist
  | FlashMessage
  | CloseButton
  | Hidden
  | SidebarLoading

type Ids
  = VisContainer
  | TutSearch
  | TutSearchInput
  | TutExplore
  | TutNodeTree
  | TutLogin
