module CssClasses exposing (..)

type Classes
  = Navbar
  | Sidebar
  | BottomBar
  | Container
  | MenuToggler
  | SidebarActive
  | SearchInput
  | NavGroup
  | Logo
  | ProgressGroup
  | ProgressBar
  | Progress
  | FontSmall
  | FontMedium
  | Controls
  | ControlIcon
  | ControlButtons
  | NowPlaying
  | AlbumCover
  | MusicTitle
  | MusicInfo
  | SoundControl
  | UserProfile
  | UserImage
  | RoundedImage
  | ArtistSongs
  | Icon
